<?php

/**
 * @file
 * Support for file media assets in GovCore.
 */

use Drupal\govcore_media\Override;
use Drupal\govcore_media_document\Plugin\media\Source\File;

/**
 * Implements hook_media_source_info_alter().
 */
function govcore_media_document_media_source_info_alter(array &$sources) {
  $sources['file']['input_match']['field_types'] = ['file'];
  Override::pluginClass($sources['file'], File::class);
}
